### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gabbygab1233** [MCarlomagno/FlutterMobilenet#13]
Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
E/flutter (25354): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoSuchMethodError: No virtual method getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/HashMap; or its super classes (declaration of 'java.util.HashMap' appears in /system/framework/core-libart.jar)
E/flutter (25354):      at sq.flutter.tflite.TflitePlugin.loadModel(TflitePlugin.java:221)
E/flutter (25354):      at sq.flutter.tflite.TflitePlugin.onMethodCall(TflitePlugin.java:95)
E/flutter (25354):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (25354):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (25354):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (25354):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (25354):      at android.os.MessageQueue.next(MessageQueue.java:150)
E/flutter (25354):      at android.os.Looper.loop(Looper.java:139)
E/flutter (25354):      at android.app.ActivityThread.main(ActivityThread.java:5541)
E/flutter (25354):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25354):      at java.lang.reflect.Method.invoke(Method.java:372)
E/flutter (25354):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
E/flutter (25354):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
E/flutter (25354): 
F/flutter (25354): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env).

**Comment by MCarlomagno** [comment]
Hi Gabby! thanks for your report! seems to be an error with the TFLite loadModel method, please check if you have the "mobilenet_v1_1.0_224.tflite" file on your assets folder, if the file exists, check if you have the correct path in the code.

Thank you!
